### ISSUE TITLE
Terraform script

### ISSUE THREAD

**Issue by jokk-itu** [jokk-itu/BookVacation#24]
- [x] DOKS Cluster
- [x] DOKS Config (Namespaces, Operator installations)
- [x] Certificate to Domain
- [x] Ingress Controller with Loadbalancer
- [x] A-Record from Domain to Loadbalancer
- [x] RabbitMQ (Cluster)
- [x] Minio (Cluster?)
- [x] RavenDB (Single Instance)
- [x] Seq (Single instance)
- [x] VacationService (Deployment, Service, ConfigMaps, Secrets, Ingress and HPA)
- [x] FlightService (Deployment, Service, ConfigMaps, Secrets, Ingress and HPA)
- [x] HotelService (Deployment, Service, ConfigMaps, Secrets, Ingress and HPA)
- [x] CarService (Deployment, Service, ConfigMaps, Secrets, Ingress and HPA)
- [x] TicketService (Deployment, Service, ConfigMaps, Secrets, Ingress and HPA)
- [x] TrackingService (Deployment, Service, ConfigMaps, Secrets, Ingress and HPA)
